service: partyyy-server

custom:
  tableName: partyyy-connections
  region: us-west-2

provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  region: ${self:custom.region}
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: '*'

functions:
  websocket-default:
    handler: src/lambdas/default.handler
    events:
      - websocket:
          route: $default
  websocket-connect:
    handler: src/lambdas/connect.handler
    events:
      - websocket:
          route: $connect
  websocket-disconnect:
    handler: src/lambdas/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocket-identify:
    handler: src/lambdas/identify.handler
    events:
      - websocket:
          route: identify
  websocket-message:
    handler: src/lambdas/message.handler
    events:
      - websocket:
          route: message

resources:
  Resources:
    WebsocketUserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
